// title has to be the same as item URL
// slug has to be the sane as subcategory URL
export const state = () => ({
  items: [
    {
      slug: 'arcs',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: 'stremnaya-arka',
      path: '/catalog/outdoor/arcs/stremnaya-arka',
      name: 'Стрёмная арка',
      type: 'arc',
      price: '5235',
      img: 'https://memegenerator.net/img/instances/400x/10993444/-.jpg',
    },
    {
      slug: 'arcs',
      description: 'ОХУЕННАЯ jj34acbaf КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: 'kosher',
      path: '/catalog/outdoor/arcs/kosher',
      name: 'Кошерная арка',
      type: 'arc',
      price: '32742',
      img:
        'https://i.pinimg.com/originals/0d/4d/b7/0d4db721dd8d34a35d82e102c031b3c9.jpg',
    },
    {
      slug: 'axes',
      description: 'ОХУЕННАЯ ji24422 КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: 'topor-tupoi',
      path: '/catalog/weapons/axes/topor-tupoi',
      name: 'Тупой топор',
      type: 'axe',
      price: '216372',
      img:
        'https://previews.123rf.com/images/janmika/janmika1110/janmika111000090/11048678-crazy-senior-woman-holding-axe-.jpg',
    },
    {
      slug: 'axes',
      description: 'ОХУЕННАЯ 242362ujfdfs КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: 'topor-ostriy',
      path: '/catalog/weapons/axes/topor-ostriy',
      name: 'Острый топор',
      type: 'axe',
      price: '217472',
      img:
        'https://staticdelivery.nexusmods.com/mods/110/images/9814-1-1329337118.png',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Стрёмный балкон',
      type: 'balcony',
      price: '12531',
      img:
        'https://cs8.pikabu.ru/images/big_size_comm/2016-07_3/1468310414143662372.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Ништяковый балкон',
      type: 'balcony',
      price: '46288',
      img:
        'https://cdn-tn.fishki.net/26/upload/post/201508/26/1641441/4b71ef71bdf5a8d2f016fa800ca528cf.jpg',
    },
    // edited one ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    {
      slug: 'banquet',
      description: 'ОХУЕННАЯ БАНКЕТКА КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: 'obossana',
      path: '/catalog/indoor/banquet/obossana',
      name: 'Обоссаная банкетка',
      type: 'banquet',
      price: '215361',
      img:
        'https://b2.3ddd.ru/media/cache/tuk_model_custom_filter_ru/model_images/0000/0000/0079/79546.53239b3804d0a.jpeg',
    },
    // end of edited one ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Не обоссаная банкетка',
      type: 'banquet',
      price: '13551',
      img:
        'https://b2.3ddd.ru/media/cache/tuk_model_custom_filter_ru/model_images/0000/0000/0079/79545.53239b38044b6.jpeg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Лавочка с бомжом',
      type: 'bench',
      price: '1500000',
      img: 'https://stihi.ru/pics/2010/11/29/5213.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Лавочка без бомжа',
      type: 'bench',
      price: '45',
      img:
        'https://static.isolux.ru/media/catalog/product/cache/1/image/602f0fa2c1f0d1ba5e241f914e856ff9/f/i/file_171_48.jpg?kar=1&kf=1&kt=1&co=1&rgb%5B0%5D=255&rgb%5B1%5D=255&rgb%5B2%5D=255&ang=ang&qua=90',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Рухлый мост',
      type: 'bridge',
      price: '2421412',
      img:
        'https://media.istockphoto.com/photos/old-broken-bridge-across-the-river-in-the-forest-picture-id495813405',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Хороший мост',
      type: 'bridge',
      price: '216743',
      img:
        'https://lh3.googleusercontent.com/proxy/pPhs8gDqNelv1nJotoWwsbJJDCdI21hWRXapDWXUrrKlilxcgjFFo10xcfSYnSCpdcqJCK06tfNiQT2oq77EpXk8dv5wz6ghKp9bD-BgsqRy2Rdh7UReF3R5HSguYg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Пасвещник',
      type: 'candlestick',
      price: '35262',
      img:
        'https://st.violity.com/auction/big/auctions/10/45/45/3/104545314.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Подсвечник',
      type: 'candlestick',
      price: '13617',
      img:
        'https://v-hram.ru/upload/iblock/fc7/fc7f6ee671315eec0c4469418770546f.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Козий рог',
      type: 'canopy',
      price: '352525',
      img:
        'https://s.alicdn.com/@sc01/kf/UTB8hyvHvFfJXKJkSamHq6zLyVXaW.jpg_300x300.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Козырек',
      type: 'canopy',
      price: '67324',
      img:
        'https://ryazan.dveri-tmk.ru/files/steel_doors/kozyrki/kozirek_k8.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Жидкий стул',
      type: 'chair',
      price: '12375',
      img:
        'https://cs9.pikabu.ru/post_img/big/2017/01/19/5/1484807307171618477.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Твердый стул',
      type: 'chair',
      price: '32746',
      img:
        'https://i.pinimg.com/736x/02/00/49/020049123ed8f08c587d031affa1fdc8.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Декорации',
      type: 'decor',
      price: '84231',
      img:
        'https://i.pinimg.com/originals/86/6f/f1/866ff18220e6bf1c3e6a9c4ff92a8dec.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Еще декорации',
      type: 'decor',
      price: '12636',
      img: 'https://www.smremont.com/upload/file_upload/images/271/1.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Забор',
      type: 'fence',
      price: '13636',
      img: 'https://zkovka.ru/images/virtuemart/product/kovanyj-zabor-33.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Запой',
      type: 'fence',
      price: '3161',
      img:
        'https://joker.ykt.ru/uploads/posts/2019-02/1549773970_52052071_2016992565055234_2688058068126137723_n.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Камин',
      type: 'fireplace',
      price: '136661',
      img:
        'https://images.ua.prom.st/1545361005_w640_h640_mramornyj-kamin-bergamo.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Эль Камино',
      type: 'fireplace',
      price: '135151',
      img: 'https://wroom.ru/i/cars2/chevrolet_elcamino_5.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Цветочек',
      type: 'flower',
      price: '536316',
      img: 'http://superkovka.by/uploads/images/kovanye-tsvety/22.png',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Цветуёчек',
      type: 'flower',
      price: '7562',
      img:
        'https://kovka.tonsakh.ru/assets/images/stati/information_items_property_116.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Подцветочник',
      type: 'flowerstand',
      price: '2623727',
      img: 'https://i.ytimg.com/vi/JZ0erQp9MqQ/maxresdefault.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Как подсвечник но для цветов',
      type: 'flowerstand',
      price: '32422',
      img:
        'https://i.pinimg.com/originals/2c/2d/72/2c2d72cc169220f4fba6183704a6a79f.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Шоколадные ворота',
      type: 'gate',
      price: '3267',
      img: 'https://st31.stpulscen.ru/images/product/190/603/572_big.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Дверь',
      type: 'gate',
      price: '326',
      img:
        'https://images.ua.prom.st/2276219490_vorota-raspashnye-zashivka.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Мангал',
      type: 'grill',
      price: '7642',
      img: 'https://images.ua.prom.st/720863719_w640_h640_mangal-kovanyj-s.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Грилль',
      type: 'grill',
      price: '3627',
      img:
        'https://canada-pechi.com.ua/image/cache/catalog/0FOTO/IMG_8586%20(1)-800x600.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Вешалка',
      type: 'hanger',
      price: '34236',
      img:
        'https://www.ot-mebel.ru/upload/resize_cache/iblock/30d/900_900_1/30def4023daaddd21c7e88b2d4e08ecb.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Вещалка',
      type: 'hanger',
      price: '3632',
      img:
        'https://kommercpr.ru/wa-data/public/shop/products/66/15/1566/images/2314/2314.750@2x.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Решетка',
      type: 'lattice',
      price: '3262',
      img:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Malbork_%28DerHexer%29_2010-07-14_176.jpg/1200px-Malbork_%28DerHexer%29_2010-07-14_176.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Калитка',
      type: 'lattice',
      price: '2362',
      img:
        'http://reshetki.kiev.ua/wp-content/uploads/2013/01/%D1%80%D0%B5%D1%88%D0%B5%D1%82%D0%BA%D0%B8-%D0%BD%D0%B0-%D0%BE%D0%BA%D0%BD%D0%B0-4.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Перила',
      type: 'railing',
      price: '23623',
      img:
        'https://i.pinimg.com/474x/48/19/05/48190546516a3d36f24b0badb48248cd.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Педрила',
      type: 'railing',
      price: '2732',
      img: 'https://chpic.su/_data/stickers_archived/PedrilaEbanaya.webp',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Что-то ритуальное',
      type: 'ritual',
      price: '1322',
      img:
        'https://i.pinimg.com/originals/2a/93/bd/2a93bd5c13d7442f3ebc20d1b46e13d2.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Вуду талисман',
      type: 'ritual',
      price: '74463643',
      img: 'https://domtalisman.ru/uploads/product/1779/loupe.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Сарай',
      type: 'shed',
      price: '235252',
      img: 'https://i.ytimg.com/vi/78KkLYxzwzY/hqdefault.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Беседка',
      type: 'shed',
      price: '6266',
      img: 'https://opennov.ru/sites/default/files/images/news/1_18.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Полка',
      type: 'shelf',
      price: '6262',
      img:
        'https://hoff.ru/upload/iblock/a5e/a5ed0a1384827c2f57a1cb8b77bf9178.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Хз чем отличается от этажерки',
      type: 'shelf',
      price: '24624',
      img:
        'https://mebelcafe.com/wp-content/uploads/2020/04/polka-nastennaya-loft-loft-600-08-art-line.com_.ua-4-min.jpg',
    },

    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Подобувник',
      type: 'shoerack',
      price: '32772',
      img: 'https://cdn.27.ua/499/30/7c/1126524_2.jpeg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Ну как подцветочник',
      type: 'shoerack',
      price: '2452',
      img:
        'http://ottointerior.com/270-large_default/belaya-polka-dlya-obuvi.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Лесенка',
      type: 'stair',
      price: '32673',
      img:
        'https://images.ru.prom.st/509680463_w640_h640_lestnitsa-s-povorotom.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Лестница',
      type: 'stair',
      price: '42367',
      img:
        'https://res.cloudinary.com/lmru/image/upload/f_auto,q_90,w_1200,h_1200,c_pad,b_white,d_photoiscoming.png/LMCode/18388365.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Качель',
      type: 'swing',
      price: '373242',
      img: 'https://vdsport.com.ua/image/cache/data/street/swing-4-600x600.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Качок',
      type: 'swing',
      price: '327732',
      img:
        'https://cdn.fishki.net/upload/post/2019/04/03/2933333/tn/9715de34a438fd64f21ea44bfd833b8d.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Нож',
      type: 'knife',
      price: '6262',
      img:
        'https://cdnimg.rg.ru/img/content/198/53/13/Mech_bronzovogo_veka_d_850.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Печь (рифмовалось с меч, но мечей больше нет)',
      type: 'knife',
      price: '24624',
      img: 'https://pechy-kaminy.ru/images/catalog/products/2832/bruno-1.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Стол',
      type: 'table',
      price: '24724',
      img: 'https://usadba-mebel.ru/images/detailed/9/Image00010.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Второй стол',
      type: 'table',
      price: '2642',
      img:
        'https://pinskdrev.by/web/catalogfiles/catalog/offers/stol_komp_format_p010_01.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Выходные группы 1',
      type: 'canopyandrailing',
      price: '34245',
      img:
        'https://thumbs.dreamstime.com/z/%D0%B8%D0%B4%D0%B8%D0%BB%D0%BB%D0%B8%D1%87%D0%BD%D1%8B%D0%B5-%D0%B2%D1%8B%D1%85%D0%BE%D0%B4%D0%BD%D1%8B%D0%B5-%D0%B4%D1%80%D1%83%D0%B7%D1%8C%D1%8F-%D0%B3%D1%80%D1%83%D0%BF%D0%BF%D1%8B-%D1%82%D1%80%D0%B0%D1%82%D1%8F%D1%82-%D0%BF%D1%80%D0%B5%D0%B4%D0%BF%D0%BE%D1%81%D1%8B%D0%BB%D0%BA%D1%83-%D0%BF%D1%80%D0%B8%D1%80%D0%BE%D0%B4%D1%8B-%D0%BB%D0%B5%D1%81%D0%B0-137833647.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Выходные группы 2',
      type: 'canopyandrailing',
      price: '12166',
      img: 'https://www.inform.kz/radmin/news/2021/01/25/210125215753822e.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Разное',
      type: 'other',
      price: '3431516',
      img: 'https://ugra.ru/pic-skovano.by/files/opora-pod-piony-1.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Безобразное',
      type: 'other',
      price: '966112',
      img: 'https://2ch.hk/by/src/14715/14207054018640.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Щит',
      type: 'shield',
      price: '24724',
      img: 'https://www.marsarmor.com/fls/shield-mars-armor.jpg',
    },
    {
      slug: '',
      description: 'ОХУЕННАЯ fhdhfsrht КУПИ СЕГОДНЯ ИЛИ Я ТЕБЯ ОБОССУ',
      title: '',
      path: '/catalog/',
      name: 'Офигенский щит',
      type: 'shield',
      price: '2642',
      img:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/%C3%89cu_%28bouclier%29.gif/220px-%C3%89cu_%28bouclier%29.gif',
    },
    {
      slug: '',
      description: '',
      title: '',
      path: '/catalog/category/subcategory/item',
      name: '',
      type: '',
      price: '',
      img: '',
    },
  ],
})
