// title has to be the same as item URL
// type has to be the same as subcategory URL
export const state = () => ({
  items: [
    {
      description: '',
      dir: 'outdoor',
      type: 'arcs',
      title: 'stremnaya-arka',
      name: 'Стрёмная арка',
      path: '/catalog/outdoor/arcs/stremnaya-arka',
      price: '',
      img: 'https://picsum.photos/200/300?random=1',
    },

    {
      description: '',
      dir: 'outdoor',
      type: 'arcs',
      title: 'kosher',
      name: 'Кошерная арка',
      path: '/catalog/outdoor/arcs/kosher',
      price: '',
      img: 'https://picsum.photos/200/300?random=2',
    },

    {
      description: '',
      dir: 'weapons',
      type: 'axes',
      title: 'topor-tupoi',
      name: 'Тупой топор',
      path: '/catalog/weapons/axes/topor-tupoi',
      price: '',
      img: 'https://picsum.photos/200/300?random=3',
    },

    {
      description: '',
      dir: 'weapons',
      type: 'axes',
      title: 'topor-ostriy',
      name: 'Острый топор',
      path: '/catalog/weapons/axes/topor-ostriy',
      price: '',
      img: 'https://picsum.photos/200/300?random=4',
    },

    {
      description: '',
      dir: 'outdoor',
      type: 'balcony',
      title: 'stremniy-balkon',
      name: 'Стрёмный балкон',
      path: '/catalog/outdoor/balcony/stremniy-balkon',
      price: '',
      img: 'https://picsum.photos/200/300?random=5',
    },

    {
      description: '',
      dir: 'outdoor',
      type: 'balcony',
      title: 'nishtyakoviy-balkon',
      name: 'Ништяковый балкон',
      path: '/catalog/outdoor/balcony/nishtyakoviy-balkon',
      price: '',
      img: 'https://picsum.photos/200/300?random=6',
    },

    {
      description: '',
      dir: 'indoor',
      type: 'banquets',
      title: 'obossana',
      name: 'Обоссаная банкетка',
      path: '/catalog/indoor/banquet/obossana',
      price: '',
      img: 'https://picsum.photos/200/300?random=7',
    },

    {
      description: '',
      dir: 'indoor',
      type: 'banquets',
      title: 'ne-obossana',
      name: 'Не обоссаная банкетка',
      path: '/catalog/indoor/banquet/ne-obossana',
      price: '',
      img: 'https://picsum.photos/200/300?random=8',
    },

    {
      description: '',
      dir: 'outdoor',
      type: 'benches',
      title: 'lavka-s-bomjom',
      name: 'Лавочка с бомжом',
      path: '/catalog/outdoor/benches/lavka-s-bomjom',
      price: '',
      img: 'https://picsum.photos/200/300?random=9',
    },

    {
      description: '',
      dir: 'indoor',
      type: 'benches',
      title: 'lavka-bez-bomja',
      name: 'Лавочка без бомжа',
      path: '/catalog/indoor/benches/lavka-bez-bomja',
      price: '',
      img: 'https://picsum.photos/200/300?random=10',
    },

    {
      description: '',
      dir: 'outdoor',
      type: 'bridges',
      title: 'ryhliy-most',
      name: 'Рухлый мост',
      path: '/catalog/outdoor/bridges/ryhliy-most',
      price: '',
      img: 'https://picsum.photos/200/300?random=11',
    },

    {
      description: '',
      dir: 'outdoor',
      type: 'bridges',
      title: 'horoshiy-most',
      name: 'Хороший мост',
      path: '/catalog/outdoor/bridges/horoshiy-most',
      price: '',
      img: 'https://picsum.photos/200/300?random=12',
    },

    {
      description: '',
      dir: 'souvenirs',
      type: 'candlesticks',
      title: 'pasveschnik',
      name: 'Пасвещник',
      path: '/catalog/souvenirs/candlesticks/pasveschnik',
      price: '',
      img: 'https://picsum.photos/200/300?random=13',
    },

    {
      description: '',
      dir: 'souvenirs',
      type: 'candlesticks',
      title: 'podsvechnik',
      name: 'Подсвечник',
      path: '/catalog/souvenirs/candlesticks/podsvechnik',
      price: '',
      img: 'https://picsum.photos/200/300?random=14',
    },

    {
      description: '',
      dir: 'outdoor',
      type: 'canopy',
      title: 'koziy-rog',
      name: 'Козий рог',
      path: '/catalog/outdoor/canopy/koziy-rog',
      price: '',
      img: 'https://picsum.photos/200/300?random=15',
    },

    {
      description: '',
      dir: 'outdoor',
      type: 'canopy',
      title: 'kozyrek',
      name: 'Козырек',
      path: '/catalog/outdoor/canopy/kozyrek',
      price: '',
      img: 'https://picsum.photos/200/300?random=16',
    },

    {
      description: '',
      dir: 'outdoor',
      type: 'chairs',
      title: 'liquid-stool',
      name: 'Жидкий стул',
      path: '/catalog/outdoor/chairs/liquid-stool',
      price: '',
      img: 'https://picsum.photos/200/300?random=17',
    },

    {
      description: '',
      dir: 'indoor',
      type: 'chairs',
      title: 'solid-stool',
      name: 'Твердый стул',
      path: '/catalog/indoor/chairs/solid-stool',
      price: '',
      img: 'https://picsum.photos/200/300?random=18',
    },

    {
      description: '',
      dir: 'indoor',
      type: 'decor',
      title: 'decoracii',
      name: 'Декорации',
      path: '/catalog/indoor/decor/decoracii',
      price: '',
      img: 'https://picsum.photos/200/300?random=19',
    },

    {
      description: '',
      dir: 'indoor',
      type: 'decor',
      title: 'eshe-decoracii',
      name: 'Еще декорации',
      path: '/catalog/indoor/decor/eshe-decoracii',
      price: '',
      img: 'https://picsum.photos/200/300?random=20',
    },

    {
      description: '',
      dir: 'outdoor',
      type: 'fences',
      title: 'zabor',
      name: 'Забор',
      path: '/catalog/outdoor/fences/zabor',
      price: '',
      img: 'https://picsum.photos/200/300?random=21',
    },

    {
      description: '',
      dir: 'outdoor',
      type: 'fences',
      title: 'zapoi',
      name: 'Запой',
      path: '/catalog/outdoor/fences/zapoi',
      price: '',
      img: 'https://picsum.photos/200/300?random=22',
    },

    {
      description: '',
      dir: 'indoor',
      type: 'fireplaces',
      title: 'kamin',
      name: 'Камин',
      path: '/catalog/indoor/fireplaces/kamin',
      price: '',
      img: 'https://picsum.photos/200/300?random=23',
    },

    {
      description: '',
      dir: 'indoor',
      type: 'fireplaces',
      title: 'el-kamino',
      name: 'Эль Камино',
      path: '/catalog/indoor/fireplaces/el-kamino',
      price: '',
      img: 'https://picsum.photos/200/300?random=24',
    },

    {
      description: '',
      dir: 'souvenirs',
      type: 'flowers',
      title: 'cvetochek',
      name: 'Цветочек',
      path: '/catalog/souvenirs/flowers/cvetochek',
      price: '',
      img: 'https://picsum.photos/200/300?random=25',
    },

    {
      description: '',
      dir: 'souvenirs',
      type: 'flowers',
      title: 'cvetuyochek',
      name: 'Цветуёчек',
      path: '/catalog/souvenirs/flowers/cvetuyochek',
      price: '',
      img: 'https://picsum.photos/200/300?random=26',
    },

    {
      description: '',
      dir: 'indoor',
      type: 'flowerstands',
      title: 'podcvetochnkik',
      name: 'Подцветочник',
      path: '/catalog/indoor/flowerstands/podcvetochnkik',
      price: '',
      img: 'https://picsum.photos/200/300?random=27',
    },

    {
      description: '',
      dir: 'outdoor',
      type: 'flowerstands',
      title: 'kak-podsechnik-no-dlya-cvetov',
      name: 'Как подсвечник но для цветов',
      path: '/catalog/outdoor/flowerstands/kak-podsechnik-no-dlya-cvetov',
      price: '',
      img: 'https://picsum.photos/200/300?random=28',
    },

    {
      description: '',
      dir: 'outdoor',
      type: 'gates',
      title: 'door',
      name: 'Шоколадные ворота',
      path: '/catalog/outdoor/gates/chocolate/door',
      price: '',
      img: 'https://picsum.photos/200/300?random=29',
    },

    {
      description: '',
      dir: 'outdoor',
      type: 'gates',
      title: 'door',
      name: 'Дверь',
      path: '/catalog/outdoor/gates/door',
      price: '',
      img: 'https://picsum.photos/200/300?random=30',
    },

    {
      description: '',
      dir: 'outdoor',
      type: 'grills',
      title: 'mangal',
      name: 'Мангал',
      path: '/catalog/outdoor/grills/mangal',
      price: '',
      img: 'https://picsum.photos/200/300?random=31',
    },

    {
      description: '',
      dir: 'outdoor',
      type: 'grills',
      title: 'grill',
      name: 'Грилль',
      path: '/catalog/outdoor/grills/grill',
      price: '',
      img: 'https://picsum.photos/200/300?random=32',
    },

    {
      description: '',
      dir: 'indoor',
      type: 'hangers',
      title: 'veshalka',
      name: 'Вешалка',
      path: '/catalog/indoor/hangers/veshalka',
      price: '',
      img: 'https://picsum.photos/200/300?random=33',
    },

    {
      description: '',
      dir: 'indoor',
      type: 'hangers',
      title: 'veschalka',
      name: 'Вещалка',
      path: '/catalog/indoor/hangers/veschalka',
      price: '',
      img: 'https://picsum.photos/200/300?random=34',
    },

    {
      description: '',
      dir: 'outdoor',
      type: 'lattices',
      title: 'reshetka',
      name: 'Решетка',
      path: '/catalog/outdoor/lattices/reshetka',
      price: '',
      img: 'https://picsum.photos/200/300?random=35',
    },

    {
      description: '',
      dir: 'outdoor',
      type: 'lattices',
      title: 'kalitka',
      name: 'Калитка',
      path: '/catalog/outdoor/lattices/kalitka',
      price: '',
      img: 'https://picsum.photos/200/300?random=36',
    },

    {
      description: '',
      dir: 'outdoor',
      type: 'railings',
      title: 'perila',
      name: 'Перила',
      path: '/catalog/outdoor/railings/perila',
      price: '',
      img: 'https://picsum.photos/200/300?random=37',
    },

    {
      description: '',
      dir: 'indoor',
      type: 'railings',
      title: 'pedrila',
      name: 'Педрила',
      path: '/catalog/indoor/railings/pedrila',
      price: '',
      img: 'https://picsum.photos/200/300?random=38',
    },

    {
      description: '',
      dir: 'ritual',
      type: 'ritual',
      title: 'chota',
      name: 'Что-то ритуальное',
      path: '/catalog/ritual/ritual/chota',
      price: '',
      img: 'https://picsum.photos/200/300?random=39',
    },

    {
      description: '',
      dir: 'ritual',
      type: 'ritual',
      title: 'voodoo',
      name: 'Вуду талисман',
      path: '/catalog/ritual/ritual/voodoo',
      price: '',
      img: 'https://picsum.photos/200/300?random=40',
    },

    {
      description: '',
      dir: 'outdoor',
      type: 'sheds',
      title: 'sarai',
      name: 'Сарай',
      path: '/catalog/outdoor/sheds/sarai',
      price: '',
      img: 'https://picsum.photos/200/300?random=41',
    },

    {
      description: '',
      dir: 'outdoor',
      type: 'sheds',
      title: 'besedka',
      name: 'Беседка',
      path: '/catalog/outdoor/sheds/besedka',
      price: '',
      img: 'https://picsum.photos/200/300?random=42',
    },
    {
      description: '',
      dir: 'indoor',
      type: 'shelves',
      title: 'polka',
      name: 'Полка',
      path: '/catalog/indoor/shelves/polka',
      price: '',
      img: 'https://picsum.photos/200/300?random=43',
    },

    {
      description: '',
      dir: 'indoor',
      type: 'shelves',
      title: 'xzpolka',
      path: '/catalog/indoor/shelves/xzpolka',
      name: 'Хз чем отличается от этажерки',
      price: '',
      img: 'https://picsum.photos/200/300?random=44',
    },

    {
      description: '',
      dir: 'indoor',
      type: 'shoeracks',
      title: 'podobuvnik',
      path: '/catalog/indoor/shoeracks/podobuvnik',
      name: 'Подобувник',
      price: '',
      img: 'https://picsum.photos/200/300?random=45',
    },

    {
      description: '',
      dir: 'indoor',
      type: 'shoeracks',
      title: 'kak-podcvetochnik',
      name: 'Ну как подцветочник',
      path: '/catalog/indoor/shoeracks/kak-podcvetochnik',
      price: '',
      img: 'https://picsum.photos/200/300?random=46',
    },

    {
      description: '',
      dir: 'indoor',
      type: 'stairs',
      title: 'lesenka',
      name: 'Лесенка',
      path: '/catalog/indoor/stairs/lesenka',
      price: '',
      img: 'https://picsum.photos/200/300?random=47',
    },

    {
      description: '',
      dir: 'outdoor',
      type: 'stairs',
      title: 'lestnica',
      name: 'Лестница',
      path: '/catalog/outdoor/stairs/lestnica',
      price: '',
      img: 'https://picsum.photos/200/300?random=48',
    },

    {
      description: '',
      dir: 'outdoor',
      type: 'swings',
      title: 'kachel',
      name: 'Качель',
      path: '/catalog/outdoor/swings/kachel',
      price: '',
      img: 'https://picsum.photos/200/300?random=49',
    },

    {
      description: '',
      dir: 'outdoor',
      type: 'swings',
      title: 'kachok',
      name: 'Качок',
      path: '/catalog/outdoor/swings/kachok',
      price: '',
      img: 'https://picsum.photos/200/300?random=50',
    },

    {
      description: '',
      dir: 'weapons',
      type: 'knives',
      title: 'nozh',
      name: 'Нож',
      path: '/catalog/weapons/nozh',
      price: '',
      img: 'https://picsum.photos/200/300?random=51',
    },

    {
      description: '',
      dir: 'weapons',
      type: 'knives',
      title: 'pech',
      name: 'Печь (рифмовалось с меч, но мечей больше нет)',
      path: '/catalog/weapons/pech',
      price: '',
      img: 'https://picsum.photos/200/300?random=52',
    },

    {
      description: '',
      dir: 'indoor',
      type: 'tables',
      title: 'stol',
      name: 'Стол',
      path: '/catalog/indoor/tables/stol',
      price: '',
      img: 'https://picsum.photos/200/300?random=53',
    },

    {
      description: '',
      dir: 'outdoor',
      type: 'tables',
      title: 'vtoroy-stol',
      name: 'Второй стол',
      path: '/catalog/outdoor/tables/vtoroy-stol',
      price: '',
      img: 'https://picsum.photos/200/300?random=54',
    },

    {
      description: '',
      dir: 'outdoor',
      type: 'canopy-and-railings',
      title: 'number1',
      name: 'Выходные группы 1',
      path: '/catalog/outdoor/canopy-and-railings/number1',
      price: '',
      img: 'https://picsum.photos/200/300?random=55',
    },

    {
      description: '',
      dir: 'outdoor',
      type: 'canopy-and-railings',
      title: 'number2',
      name: 'Выходные группы 2',
      path: '/catalog/outdoor/canopy-and-railings/number2',
      price: '',
      img: 'https://picsum.photos/200/300?random=56',
    },

    {
      description: '',
      dir: 'souvenirs',
      type: 'other',
      title: 'raznoe',
      name: 'Разное',
      path: '/catalog/souvenirs/other/raznoe',
      price: '',
      img: 'https://picsum.photos/200/300?random=57',
    },

    {
      description: '',
      dir: 'souvenirs',
      type: 'other',
      title: 'bezobraznoe',
      name: 'Безобразное',
      path: '/catalog/souvenirs/other/bezobraznoe',
      price: '',
      img: 'https://picsum.photos/200/300?random=58',
    },

    {
      description: '',
      dir: 'weapons',
      type: 'shields',
      title: 'shield',
      name: 'Щит',
      path: '/catalog/weapons/shields/shield',
      price: '',
      img: 'https://picsum.photos/200/300?random=59',
    },

    {
      description: '',
      dir: 'weapons',
      type: 'shields',
      title: 'awesome-shield',
      name: 'Офигенский щит',
      path: '/catalog/weapons/shields/awesome-shield',
      price: '',
      img: 'https://picsum.photos/200/300?random=60',
    },

    {
      description: '',
      dir: '',
      type: '',
      title: '',
      name: '',
      path: '/catalog/category/subcategory/item',
      price: '',
      img: '',
    },
  ],
})
