export const state = () => ({
  subCategories: [
    {
      name: 'Арки',
      link: '/catalog/outdoor/arcs',
      type: 'outdoor',
      featured: true,
      img: 'https://picsum.photos/200/300?random=61',
      description: 'Описание категории',
      title: 'arcs',
    },
    {
      name: 'Топоры',
      link: '/catalog/weapons/axes',
      type: 'weapons',
      featured: true,
      img: 'https://picsum.photos/200/300?random=62',
      description: 'Описание категории',
      title: 'axes',
    },
    {
      name: 'Балконы',
      link: '/catalog/outdoor/balcony',
      type: 'outdoor',
      featured: true,
      img: 'https://picsum.photos/200/300?random=63',
      description: 'Описание категории',
      title: 'balcony',
    },
    {
      name: 'Банкетки',
      link: '/catalog/indoor/banquets',
      type: 'indoor',
      featured: true,
      img: 'https://picsum.photos/200/300?random=64',
      description: 'Описание категории',
      title: 'banquets',
    },
    {
      name: 'Скамейки',
      link: '/catalog/indoor/benches',
      type: 'indoor',
      featured: true,
      img: 'https://picsum.photos/200/300?random=65',
      description: 'Описание категории',
      title: 'benches',
    },
    {
      name: 'Скамейки',
      link: '/catalog/outdoor/benches',
      type: 'outdoor',
      featured: false,
      img: 'https://picsum.photos/200/300?random=66',
      description: 'Описание категории',
      title: 'benches',
    },
    {
      name: 'Мостики',
      link: '/catalog/outdoor/bridges',
      type: 'outdoor',
      featured: true,
      img: 'https://picsum.photos/200/300?random=67',
      description: 'Описание категории',
      title: 'bridges',
    },
    {
      name: 'Подсвечники',
      link: '/catalog/souvenirs/candlesticks',
      type: 'souvenirs',
      featured: true,
      img: 'https://picsum.photos/200/300?random=68',
      description: 'Описание категории',
      title: 'candlesticks',
    },
    {
      name: 'Навесы',
      link: '/catalog/outdoor/canopy',
      type: 'outdoor',
      featured: true,
      img: 'https://picsum.photos/200/300?random=69',
      description: 'Описание категории',
      title: 'canopy',
    },
    {
      name: 'Выходные группы',
      link: '/catalog/outdoor/canopy-and-railings',
      type: 'outdoor',
      featured: false,
      img: 'https://picsum.photos/200/300?random=70',
      description: 'Описание категории',
      title: 'canopy-and-railings',
    },
    {
      name: 'Стулья',
      link: '/catalog/indoor/chairs',
      type: 'indoor',
      featured: true,
      img: 'https://picsum.photos/200/300?random=71',
      description: 'Описание категории',
      title: 'chairs',
    },
    {
      name: 'Декор',
      link: '/catalog/indoor/decor',
      type: 'indoor',
      featured: true,
      img: 'https://picsum.photos/200/300?random=72',
      description: 'Описание категории',
      title: 'decor',
    },
    {
      name: 'Каминные наборы',
      link: '/catalog/indoor/fireplaces',
      type: 'indoor',
      featured: false,
      img: 'https://picsum.photos/200/300?random=74',
      description: 'Описание категории',
      title: 'fireplaces',
    },
    {
      name: 'Заборы',
      link: '/catalog/outdoor/fences',
      type: 'outdoor',
      featured: true,
      img: 'https://picsum.photos/200/300?random=73',
      description: 'Описание категории',
      title: 'fences',
    },
    {
      name: 'Цветы',
      link: '/catalog/souvenirs/flowers',
      type: 'souvenirs',
      featured: true,
      img: 'https://picsum.photos/200/300?random=75',
      description: 'Описание категории',
      title: 'flowers',
    },
    {
      name: 'Разное',
      link: '/catalog/souvenirs/other',
      type: 'souvenirs',
      featured: true,
      img: 'https://picsum.photos/200/300?random=76',
      description: 'Описание категории',
      title: 'other',
    },
    {
      name: 'Кашпо',
      link: '/catalog/indoor/flowerstands',
      type: 'indoor',
      featured: true,
      img: 'https://picsum.photos/200/300?random=77',
      description: 'Описание категории',
      title: 'flowerstands',
    },
    {
      name: 'Кашпо',
      link: '/catalog/outdoor/flowerstands',
      type: 'outdoor',
      featured: false,
      img: 'https://picsum.photos/200/300?random=78',
      description: 'Описание категории',
      title: 'flowerstands',
    },
    {
      name: 'Ворота',
      link: '/catalog/outdoor/gates',
      type: 'outdoor',
      featured: true,
      img: 'https://picsum.photos/200/300?random=79',
      description: 'Описание категории',
      title: 'gates',
    },
    {
      name: 'Мангалы',
      link: '/catalog/outdoor/grills',
      type: 'outdoor',
      featured: true,
      img: 'https://picsum.photos/200/300?random=80',
      description: 'Описание категории',
      title: 'grills',
    },
    {
      name: 'Вешалки',
      link: '/catalog/indoor/hangers',
      type: 'indoor',
      featured: true,
      img: 'https://picsum.photos/200/300?random=81',
      description: 'Описание категории',
      title: 'hangers',
    },
    {
      name: 'Решетки',
      link: '/catalog/outdoor/lattices',
      type: 'outdoor',
      featured: true,
      img: 'https://picsum.photos/200/300?random=82',
      description: 'Описание категории',
      title: 'lattices',
    },
    {
      name: 'Перила',
      link: '/catalog/indoor/railings',
      type: 'indoor',
      featured: false,
      img: 'https://picsum.photos/200/300?random=83',
      description: 'Описание категории',
      title: 'railings',
    },
    {
      name: 'Перила',
      link: '/catalog/outdoor/railings',
      type: 'outdoor',
      featured: true,
      img: 'https://picsum.photos/200/300?random=84',
      description: 'Описание категории',
      title: 'railings',
    },

    {
      name: 'Беседки',
      link: '/catalog/outdoor/sheds',
      type: 'outdoor',
      featured: true,
      img: 'https://picsum.photos/200/300?random=85',
      description: 'Описание категории',
      title: 'sheds',
    },
    {
      name: 'Этажерки',
      link: '/catalog/indoor/shelves',
      type: 'indoor',
      featured: true,
      img: 'https://picsum.photos/200/300?random=86',
      description: 'Описание категории',
      title: 'shelves',
    },

    {
      name: 'Обувницы',
      link: '/catalog/indoor/shoeracks',
      type: 'indoor',
      featured: true,
      img: 'https://picsum.photos/200/300?random=87',
      description: 'Описание категории',
      title: 'shoeracks',
    },
    {
      name: 'Лестницы',
      link: '/catalog/indoor/stairs',
      type: 'indoor',
      featured: true,
      img: 'https://picsum.photos/200/300?random=88',
      description: 'Описание категории',
      title: 'stairs',
    },
    {
      name: 'Лестницы',
      link: '/catalog/outdoor/stairs',
      type: 'outdoor',
      featured: false,
      img: 'https://picsum.photos/200/300?random=89',
      description: 'Описание категории',
      title: 'stairs',
    },
    {
      name: 'Качели',
      link: '/catalog/outdoor/swings',
      type: 'outdoor',
      featured: true,
      img: 'https://picsum.photos/200/300?random=90',
      description: 'Описание категории',
      title: 'swings',
    },
    {
      name: 'Ножи',
      link: '/catalog/weapons/knives',
      type: 'weapons',
      featured: true,
      img: 'https://picsum.photos/200/300?random=91',
      description: 'Описание категории',
      title: 'knives',
    },
    {
      name: 'Столы',
      link: '/catalog/indoor/tables',
      type: 'indoor',
      featured: false,
      img: 'https://picsum.photos/200/300?random=92',
      description: 'Описание категории',
      title: 'tables',
    },
    {
      name: 'Столы',
      link: '/catalog/outdoor/tables',
      type: 'outdoor',
      featured: true,
      img: 'https://picsum.photos/200/300?random=93',
      description: 'Описание категории',
      title: 'tables',
    },
    {
      name: 'Щиты',
      link: '/catalog/weapons/shields',
      type: 'weapons',
      featured: true,
      img: 'https://picsum.photos/200/300?random=94',
      description: 'Описание категории',
      title: 'shields',
    },
    {
      name: 'Ритуальные изделия',
      link: '/catalog/ritual/ritual',
      type: 'ritual',
      featured: false,
      img: 'https://picsum.photos/200/300?random=95',
      description: 'Описание категории',
      title: 'ritual',
    },
  ],
})
