export const state = () => ({
  subCategories: [
    {
      name: 'Арки',
      link: '/catalog/outdoor/arcs',
      type: 'outdoor',
      featured: true,
    },
    {
      name: 'Топоры',
      link: '/catalog/weapons/axes',
      type: 'weapons',
      featured: false,
    },
    {
      name: 'Балконы',
      link: '/catalog/outdoor/balcony',
      type: 'outdoor',
      featured: true,
    },
    {
      name: 'Банкетки',
      link: '/catalog/indoor/banquet',
      type: 'indoor',
      featured: true,
    },
    {
      name: 'Скамейки',
      link: '/catalog/outdoor/benches',
      type: 'indoor',
      featured: true,
    },
    {
      name: 'Скамейки',
      link: '/catalog/indoor/benches',
      type: 'outdoor',
      featured: false,
    },
    {
      name: 'Мостики',
      link: '/catalog/outdoor/bridges',
      type: 'outdoor',
      featured: true,
    },
    {
      name: 'Подсвечники',
      link: '/catalog/souvenir/candlestick',
      type: 'souvenir',
      featured: true,
    },
    {
      name: 'Навесы и козырьки',
      link: '/catalog/outdoor/canopy',
      type: 'outdoor',
      featured: true,
    },
    {
      name: 'Выходные группы',
      link: '/catalog/outdoor/canopy-and-railings',
      type: 'outdoor',
      featured: true,
    },
    {
      name: 'Стулья',
      link: '/catalog/indoor/chairs',
      type: 'indoor',
      featured: true,
    },
    {
      name: 'Декор',
      link: '/catalog/indoor/decor',
      type: 'indoor',
      featured: true,
    },
    {
      name: 'Заборы',
      link: '/catalog/outdoor/fences',
      type: 'outdoor',
      featured: true,
    },
    {
      name: 'Каминные наборы',
      link: '/catalog/indoor/fireplace',
      type: 'indoor',
      featured: true,
    },
    {
      name: 'Цветы',
      link: '/catalog/souvenir/flowers',
      type: 'souvenir',
      featured: true,
    },
    {
      name: 'Разное',
      link: '/catalog/souvenir/other',
      type: 'souvenir',
      featured: false,
    },
    {
      name: 'Подставки под цветы',
      link: '/catalog/outdoor/flowerstands',
      type: 'indoor',
      featured: true,
    },
    {
      name: 'Подставки под цветы',
      link: '/catalog/indoor/flowerstands',
      type: 'outdoor',
      featured: true,
    },
    {
      name: 'Ворота',
      link: '/catalog/outdoor/gates',
      type: 'outdoor',
      featured: true,
    },
    {
      name: 'Мангалы и коптильни',
      link: '/catalog/outdoor/grills',
      type: 'outdoor',
      featured: true,
    },
    {
      name: 'Вешалки',
      link: '/catalog/indoor/hangers',
      type: 'indoor',
      featured: true,
    },
    {
      name: 'Решетки на окна',
      link: '/catalog/outdoor/lattice',
      type: 'outdoor',
      featured: true,
    },
    {
      name: 'Перила',
      link: '/catalog/indoor/railings',
      type: 'indoor',
      featured: false,
    },
    {
      name: 'Перила',
      link: '/catalog/outdoor/railings',
      type: 'outdoor',
      featured: true,
    },

    {
      name: 'Беседки',
      link: '/catalog/outdoor/shed',
      type: 'outdoor',
      featured: true,
    },
    {
      name: 'Этажерки',
      link: '/catalog/indoor/shelves',
      type: 'indoor',
      featured: true,
    },

    {
      name: 'Обувницы',
      link: '/catalog/indoor/shoeracks',
      type: 'indoor',
      featured: true,
    },
    {
      name: 'Лестницы',
      link: '/catalog/indoor/stairs',
      type: 'indoor',
      featured: true,
    },
    {
      name: 'Лестницы',
      link: '/catalog/outdoor/stairs',
      type: 'outdoor',
      featured: false,
    },
    {
      name: 'Качели',
      link: '/catalog/outdoor/swings',
      type: 'outdoor',
      featured: true,
    },
    {
      name: 'Ножи',
      link: '/catalog/weapons/knives',
      type: 'weapons',
      featured: false,
    },
    {
      name: 'Столы',
      link: '/catalog/indoor/tables',
      type: 'indoor',
      featured: false,
    },
    {
      name: 'Столы',
      link: '/catalog/outdoor/tables',
      type: 'outdoor',
      featured: true,
    },
    {
      name: 'Щиты',
      link: '/catalog/weapons/shields',
      type: 'weapons',
      featured: false,
    },
  ],
})
